### ISSUE TITLE
Fail to install newer Nginx on Debian 7

### ISSUE THREAD

**Issue by buunguyen** [geerlingguy/ansible-role-nginx#29] opened 2015-09-24 19:46 UTC
I'm running Debian 7 and setting `nginx_default_release: "wheezy-backports"` per instruction in the README to install a newer version of Nginx, but received this error

> SystemError: E:The value 'wheezy-backports' is invalid for APT::Default-Release as such a release is not available in the sources

Any idea?

**Comment by geerlingguy** [comment] 2016-01-22 15:40
I'm going to close this and mark as a duplicate of #27 — using the official PPA will allow for newer versions to be installed more easily. For your particular issue, make sure wheezy-backports is in your list of apt sources (see this post for an example: http://antler.co.za/2014/10/install-debian-wheezy-backports-repository/).

**Closed by geerlingguy** 2016-01-22 15:40 UTC
